const list =[
    {
        id:1,
        name: "BMW",
        img: "https://www.freeiconspng.com/uploads/black-cool-bmw-car-png-19.png",
        model: "7 Series",
        description: "Refill fuel at the end of the day or pay PKR 40/KM",
        price: "1500",
        daysAvailable: "6 Days",
        bluetooth: "Yes",
        usbPort: "No",
        gps: "Yes",
        ac: "Yes",
      },
      {
        id:2,
        name: "DAEWOO",
        img: "https://pngimg.com/d/daewoo_PNG8.png",
        model: "Racer",
        description: "Refill fuel at the end of the day or pay PKR 40/KM",
        Type: "Private (1935-65)",
        industry: "Automotive",
        price: "1350",
        daysAvailable: "6 Days",
        bluetooth: "Yes",
        usbPort: "Yes",
        gps: "Yes",
        ac: "No",
      },
      {
        id:3,
        name: "DAIHATSU",
        img: "https://www.daihatsu.com/news/2018/scj6mq0000001rye-img/2.png",
        model: "Charade",
        description: "Refill fuel at the end of the day or pay PKR 40/KM",
        daysAvailable: "6 Days",
        bluetooth: "Yes",
        usbPort: "No",
        gps: "Yes",
        ac: "Yes",
      },
      {
        id:4,
        name: "HONDA",
        img: "https://www.freepnglogos.com/uploads/honda-car-png/honda-car-honda-accord-hybrid-gets-more-power-improved-2.png",
        model: "Accord",
        description: "Refill fuel at the end of the day or pay PKR 40/KM",
        price: "1650",
        daysAvailable: "6 Days",
        bluetooth: "Yes",
        usbPort: "No",
        gps: "Yes",
        ac: "No",
      },
      {
        id:5,
        name: "HONDA",
        img: "https://cache2.pakwheels.com/ad_pictures/8014/honda-city-1-2l-cvt-2023-80143412.jpg",
        model: "City IVTEC",
        description: "Refill fuel at the end of the day or pay PKR 40/KM",
        price: "1200",
        daysAvailable: "5 Days",
        bluetooth: "",
        usbPort: "Yes",
        gps: "Yes",
        ac: "Yes",
      },
      {
        id:6,
        name: "VOLVO",
        img: "https://www.pngmart.com/files/4/Volvo-Xc90-PNG-Transparent.png",
        model: "Volvo Xc90",
        description: "Refill fuel at the end of the day or pay PKR 40/KM",
        price: "1300",
        daysAvailable: "6 Days",
        bluetooth: "",
        usbPort: "",
        gps: "Yes",
        ac: "Yes",
      },
]